version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
    groups:
      kotlin:
        patterns:
          - "jvm"
          - "plugin.allopen"
          - "plugin.serialization"
      quarkus:
        patterns:
          - "io.quarkus"
          - "io.quarkus.platform:quarkus-bom"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
