name: api

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - prod

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  build:
    name: Gradle Build
    runs-on: ${{ matrix.architecture == 'arm64' && 'blacksmith-2vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    permissions:
      contents: read
      checks: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java 21
        uses: useblacksmith/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: useblacksmith/setup-gradle/setup-gradle@v6
        with:
          gradle-version: wrapper
      - name: Build
        run: make ci/build/app/native
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.architecture }}
          path: |
            build/*-runner
            build/quarkus-app/
          if-no-files-found: error
  test:
    name: Gradle Test
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java 21
        uses: useblacksmith/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: useblacksmith/setup-gradle/setup-gradle@v6
        with:
          gradle-version: wrapper
      - name: Get Build
        uses: actions/download-artifact@v4
        with:
          name: build-amd64
          path: build
      - name: Test
        run: make ci/test/app/native
  push:
    name: Push to GitHub Container Registry
    runs-on: ${{ matrix.architecture == 'arm64' && 'blacksmith-2vcpu-ubuntu-2204-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    needs: [build]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup java 21
      uses: useblacksmith/setup-java@v5
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: useblacksmith/setup-gradle/setup-gradle@v6
      with:
        gradle-version: wrapper
    - name: Setup variables
      id: vars
      run: |
        echo "VERSION=$(date +"%Y_%m_%d")_$(echo ${{ github.ref }} | sed 's:.*/::')_$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "DOCKER_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}" >> $GITHUB_OUTPUT
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Get Build
      uses: actions/download-artifact@v4
      with:
        name: build-${{ matrix.architecture }}
        path: build
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./src/main/docker/Dockerfile.native-micro
        push: true
        tags: ${{ steps.vars.outputs.DOCKER_IMAGE }}:${{ steps.vars.outputs.VERSION }}_${{ matrix.architecture }}
